-- PROJECT PILOT 4.1 CUMULATIVE UPGRADE
-- Generated August 16, 2026.
-- Safe path for the existing Project Pilot database when you are unsure whether Sprint 3.3, 3.6, or 4.0 was installed.
-- This script reapplies the idempotent 015 + 016 + 017 + 018 schema upgrades in order.

DO $$
BEGIN
  IF to_regclass('public.permit_cases') IS NULL OR to_regclass('public.profiles') IS NULL OR to_regclass('public.projects') IS NULL THEN
    RAISE EXCEPTION 'This database is missing the Project Pilot base schema. Use RUN_THIS_IN_SUPABASE_FRESH_4_1.sql for a new database instead.';
  END IF;
END $$;


-- ============================================================================
-- BEGIN 015_permit_application_builder_3_3.sql
-- ============================================================================
-- Project Pilot Sprint 3.3
-- Permit Application Builder: reviewed application packets, portal-entry progress,
-- export history, and applicant review audit fields.
-- Run after migrations 012, 013, and 014.

create extension if not exists "pgcrypto";

alter table public.permit_cases
  add column if not exists application_packet_version text not null default '',
  add column if not exists application_packet_generated_at timestamptz,
  add column if not exists application_packet_status text not null default 'not_started',
  add column if not exists portal_field_progress jsonb not null default '{}'::jsonb,
  add column if not exists applicant_review_name text not null default '',
  add column if not exists applicant_review_confirmed_at timestamptz;

do $$
begin
  alter table public.permit_cases
    add constraint permit_cases_application_packet_status_check
    check (application_packet_status in ('not_started','draft','ready','exported','portal_entry','submitted'));
exception
  when duplicate_object then null;
end $$;

create table if not exists public.permit_application_exports (
  id uuid primary key default gen_random_uuid(),
  permit_case_id uuid not null references public.permit_cases(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  export_type text not null default 'packet_snapshot' check (export_type in ('packet_snapshot','printable_html','portal_field_map','structured_json')),
  packet_version text not null default '',
  packet_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.permit_application_exports enable row level security;

drop policy if exists "Project owners can view permit application exports" on public.permit_application_exports;
create policy "Project owners can view permit application exports"
on public.permit_application_exports for select to authenticated
using ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

drop policy if exists "Project owners can create permit application exports" on public.permit_application_exports;
create policy "Project owners can create permit application exports"
on public.permit_application_exports for insert to authenticated
with check ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

drop policy if exists "Project owners can delete permit application exports" on public.permit_application_exports;
create policy "Project owners can delete permit application exports"
on public.permit_application_exports for delete to authenticated
using ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

grant select, insert, delete on public.permit_application_exports to authenticated;

create index if not exists permit_application_exports_case_idx
  on public.permit_application_exports(permit_case_id, created_at desc);
create index if not exists permit_application_exports_user_idx
  on public.permit_application_exports(user_id, created_at desc);

comment on table public.permit_application_exports is
'Immutable snapshots of homeowner-reviewed permit application packets generated by Project Pilot. Official submission, signatures, identity verification, professional seals, and government payments remain controlled by the applicant, authorized professional, or governing authority.';

-- END 015_permit_application_builder_3_3.sql

-- ============================================================================
-- BEGIN 016_full_service_permit_operations_3_6.sql
-- ============================================================================
-- Project Pilot Sprint 3.6
-- Full-Service Permit Operations
-- Run AFTER migrations 012, 013, 014, and 015.
--
-- Purpose:
-- Turn Permit Concierge into an auditable full-service permit operations workflow:
-- intake -> jurisdiction verification -> preparation -> allowed filing assistance/submission
-- -> corrections -> inspections -> closeout.
--
-- IMPORTANT: This schema records authorization and operational work. It does not override
-- government rules that require the applicant's own login, signature, identity verification,
-- professional seal, licensed trade credential, notarization, or payment.

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- Expand Permit Concierge request records for full-service operations.
-- -----------------------------------------------------------------------------
alter table public.permit_concierge_requests
  add column if not exists case_number text,
  add column if not exists service_mode text not null default 'full_service',
  add column if not exists current_phase text not null default 'intake',
  add column if not exists agency_name text not null default '',
  add column if not exists agency_url text not null default '',
  add column if not exists filing_mode text not null default 'unknown',
  add column if not exists requirement_flags jsonb not null default '{"applicant_login":"unknown","signature":"unknown","identity_verification":"unknown","government_payment":"unknown","professional_seal":"unknown"}'::jsonb,
  add column if not exists customer_action_reason text not null default '',
  add column if not exists last_government_update_at timestamptz,
  add column if not exists service_started_at timestamptz,
  add column if not exists service_completed_at timestamptz;

create unique index if not exists permit_concierge_requests_case_number_uidx
  on public.permit_concierge_requests(case_number)
  where case_number is not null and case_number <> '';

-- Expand the existing status check safely.
do $$
begin
  alter table public.permit_concierge_requests
    drop constraint if exists permit_concierge_requests_status_check;

  alter table public.permit_concierge_requests
    add constraint permit_concierge_requests_status_check
    check (status in (
      'requested','intake_review','preparing','waiting_on_homeowner','ready_for_submission',
      'filing','submitted','corrections','approved','inspections','closeout','closed','cancelled'
    ));
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.permit_concierge_requests
    add constraint permit_concierge_requests_service_mode_check
    check (service_mode in ('full_service','guided'));
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.permit_concierge_requests
    add constraint permit_concierge_requests_filing_mode_check
    check (filing_mode in ('unknown','coordinator_allowed','applicant_required','mixed'));
exception
  when duplicate_object then null;
end $$;

-- -----------------------------------------------------------------------------
-- Immutable customer authorization record for the full-service workflow.
-- -----------------------------------------------------------------------------
create table if not exists public.permit_service_authorizations (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.permit_concierge_requests(id) on delete cascade,
  permit_case_id uuid not null references public.permit_cases(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  authorization_version text not null default '3.6',
  signer_name text not null,
  signer_email text not null,
  scopes jsonb not null default '{}'::jsonb,
  acknowledgements jsonb not null default '{}'::jsonb,
  accepted_at timestamptz not null default now(),
  revoked_at timestamptz,
  revocation_note text not null default '',
  created_at timestamptz not null default now()
);

create unique index if not exists permit_service_authorizations_request_version_uidx
  on public.permit_service_authorizations(request_id, authorization_version);

-- -----------------------------------------------------------------------------
-- Homeowner-visible + internal case timeline.
-- -----------------------------------------------------------------------------
create table if not exists public.permit_concierge_events (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.permit_concierge_requests(id) on delete cascade,
  permit_case_id uuid not null references public.permit_cases(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null default 'update',
  title text not null,
  detail text not null default '',
  source text not null default 'project_pilot',
  visible_to_homeowner boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Structured correction rounds.
-- -----------------------------------------------------------------------------
create table if not exists public.permit_concierge_corrections (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.permit_concierge_requests(id) on delete cascade,
  permit_case_id uuid not null references public.permit_cases(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  round_number integer not null default 1,
  agency_reference text not null default '',
  notice_text text not null default '',
  plain_language_summary text not null default '',
  response_plan text not null default '',
  status text not null default 'received' check (status in ('received','reviewing','waiting_on_homeowner','response_ready','resubmitted','resolved')),
  due_at timestamptz,
  received_at timestamptz not null default now(),
  resubmitted_at timestamptz,
  resolved_at timestamptz,
  visible_to_homeowner boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Structured inspection and closeout tracking.
-- -----------------------------------------------------------------------------
create table if not exists public.permit_concierge_inspections (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.permit_concierge_requests(id) on delete cascade,
  permit_case_id uuid not null references public.permit_cases(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  inspection_type text not null,
  agency_name text not null default '',
  status text not null default 'not_ready' check (status in ('not_ready','ready_to_schedule','scheduled','passed','failed','cancelled','not_required')),
  scheduled_at timestamptz,
  result_notes text not null default '',
  homeowner_preparation text not null default '',
  visible_to_homeowner boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Jurisdiction playbooks: admin-only operating knowledge.
-- A playbook must be verified before staff rely on it for a live filing decision.
-- -----------------------------------------------------------------------------
create table if not exists public.permit_jurisdiction_playbooks (
  id uuid primary key default gen_random_uuid(),
  jurisdiction_key text not null,
  jurisdiction_label text not null,
  project_type text not null default 'general',
  status text not null default 'draft' check (status in ('draft','verified','paused')),
  agency_name text not null default '',
  portal_url text not null default '',
  submission_channel text not null default '',
  filing_mode text not null default 'unknown' check (filing_mode in ('unknown','coordinator_allowed','applicant_required','mixed')),
  requirements jsonb not null default '{}'::jsonb,
  source_urls jsonb not null default '[]'::jsonb,
  operating_notes text not null default '',
  verified_at timestamptz,
  verified_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (jurisdiction_key, project_type)
);

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
alter table public.permit_service_authorizations enable row level security;
alter table public.permit_concierge_events enable row level security;
alter table public.permit_concierge_corrections enable row level security;
alter table public.permit_concierge_inspections enable row level security;
alter table public.permit_jurisdiction_playbooks enable row level security;

-- Authorization: owner can read; admin can operate. Creation is done by the server route.
drop policy if exists "Owners can view permit service authorizations" on public.permit_service_authorizations;
create policy "Owners can view permit service authorizations"
on public.permit_service_authorizations for select to authenticated
using ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

drop policy if exists "Admins can manage permit service authorizations" on public.permit_service_authorizations;
create policy "Admins can manage permit service authorizations"
on public.permit_service_authorizations for all to authenticated
using (public.is_project_pilot_admin())
with check (public.is_project_pilot_admin());

-- Events: owners see only customer-visible events; admins see/manage all.
drop policy if exists "Owners can view permit concierge events" on public.permit_concierge_events;
create policy "Owners can view permit concierge events"
on public.permit_concierge_events for select to authenticated
using (((user_id = auth.uid() and public.owns_project(project_id)) and visible_to_homeowner = true) or public.is_project_pilot_admin());

drop policy if exists "Admins can manage permit concierge events" on public.permit_concierge_events;
create policy "Admins can manage permit concierge events"
on public.permit_concierge_events for all to authenticated
using (public.is_project_pilot_admin())
with check (public.is_project_pilot_admin());

-- Corrections.
drop policy if exists "Owners can view permit concierge corrections" on public.permit_concierge_corrections;
create policy "Owners can view permit concierge corrections"
on public.permit_concierge_corrections for select to authenticated
using (((user_id = auth.uid() and public.owns_project(project_id)) and visible_to_homeowner = true) or public.is_project_pilot_admin());

drop policy if exists "Admins can manage permit concierge corrections" on public.permit_concierge_corrections;
create policy "Admins can manage permit concierge corrections"
on public.permit_concierge_corrections for all to authenticated
using (public.is_project_pilot_admin())
with check (public.is_project_pilot_admin());

-- Inspections.
drop policy if exists "Owners can view permit concierge inspections" on public.permit_concierge_inspections;
create policy "Owners can view permit concierge inspections"
on public.permit_concierge_inspections for select to authenticated
using (((user_id = auth.uid() and public.owns_project(project_id)) and visible_to_homeowner = true) or public.is_project_pilot_admin());

drop policy if exists "Admins can manage permit concierge inspections" on public.permit_concierge_inspections;
create policy "Admins can manage permit concierge inspections"
on public.permit_concierge_inspections for all to authenticated
using (public.is_project_pilot_admin())
with check (public.is_project_pilot_admin());

-- Playbooks are intentionally admin-only.
drop policy if exists "Admins can manage permit jurisdiction playbooks" on public.permit_jurisdiction_playbooks;
create policy "Admins can manage permit jurisdiction playbooks"
on public.permit_jurisdiction_playbooks for all to authenticated
using (public.is_project_pilot_admin())
with check (public.is_project_pilot_admin());

-- Grants. RLS remains the controlling layer for authenticated users.
grant select on public.permit_service_authorizations to authenticated;
grant select, insert, update, delete on public.permit_concierge_events to authenticated;
grant select, insert, update, delete on public.permit_concierge_corrections to authenticated;
grant select, insert, update, delete on public.permit_concierge_inspections to authenticated;
grant select, insert, update, delete on public.permit_jurisdiction_playbooks to authenticated;

-- Indexes.
create index if not exists permit_service_authorizations_request_idx
  on public.permit_service_authorizations(request_id, accepted_at desc);
create index if not exists permit_concierge_events_request_idx
  on public.permit_concierge_events(request_id, created_at desc);
create index if not exists permit_concierge_corrections_request_idx
  on public.permit_concierge_corrections(request_id, status, created_at desc);
create index if not exists permit_concierge_inspections_request_idx
  on public.permit_concierge_inspections(request_id, status, scheduled_at);
create index if not exists permit_jurisdiction_playbooks_lookup_idx
  on public.permit_jurisdiction_playbooks(jurisdiction_key, project_type, status);

-- Touch updated_at helpers.
create or replace function public.touch_permit_operations_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists permit_concierge_corrections_touch on public.permit_concierge_corrections;
create trigger permit_concierge_corrections_touch
before update on public.permit_concierge_corrections
for each row execute function public.touch_permit_operations_updated_at();

drop trigger if exists permit_concierge_inspections_touch on public.permit_concierge_inspections;
create trigger permit_concierge_inspections_touch
before update on public.permit_concierge_inspections
for each row execute function public.touch_permit_operations_updated_at();

drop trigger if exists permit_jurisdiction_playbooks_touch on public.permit_jurisdiction_playbooks;
create trigger permit_jurisdiction_playbooks_touch
before update on public.permit_jurisdiction_playbooks
for each row execute function public.touch_permit_operations_updated_at();

comment on table public.permit_service_authorizations is
'Immutable customer authorization record for Project Pilot full-service permit coordination. It records allowed administrative scopes and explicit applicant-controlled boundaries.';
comment on table public.permit_concierge_events is
'Auditable full-service permit timeline. Homeowners see only visible_to_homeowner events.';
comment on table public.permit_concierge_corrections is
'Structured government correction rounds and Project Pilot response workflow.';
comment on table public.permit_concierge_inspections is
'Structured inspection scheduling, preparation, result, and closeout tracking.';
comment on table public.permit_jurisdiction_playbooks is
'Admin-only verified operating playbooks for jurisdiction/project-type permit handling. Draft records must not be treated as verified filing authority.';

-- END 016_full_service_permit_operations_3_6.sql

-- ============================================================================
-- BEGIN 017_revenue_completion_4_0.sql
-- ============================================================================
-- Project Pilot 4.0 Launch Revenue
-- Adds paid Full-Service Permit Concierge orders while preserving free planning
-- and the existing contractor-introduction marketplace.
-- Run after migrations 015 and 016.

create extension if not exists "pgcrypto";

alter table public.permit_concierge_requests
  add column if not exists payment_status text not null default 'waived',
  add column if not exists service_fee_cents integer not null default 0,
  add column if not exists revenue_order_id uuid,
  add column if not exists paid_at timestamptz;

do $$
begin
  alter table public.permit_concierge_requests
    add constraint permit_concierge_requests_payment_status_check
    check (payment_status in ('pending','paid','waived','refunded','cancelled'));
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.permit_concierge_requests
    add constraint permit_concierge_requests_service_fee_nonnegative_check
    check (service_fee_cents >= 0);
exception
  when duplicate_object then null;
end $$;

create table if not exists public.permit_service_orders (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.permit_concierge_requests(id) on delete cascade,
  permit_case_id uuid not null references public.permit_cases(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  service_code text not null default 'full_service_permit_coordination',
  amount_cents integer not null check (amount_cents > 0),
  currency text not null default 'usd',
  status text not null default 'pending' check (status in ('pending','paid','refunded','cancelled','waived')),
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  paid_at timestamptz,
  refunded_at timestamptz,
  cancelled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists permit_service_orders_checkout_uidx
  on public.permit_service_orders(stripe_checkout_session_id)
  where stripe_checkout_session_id is not null;
create index if not exists permit_service_orders_request_idx
  on public.permit_service_orders(request_id, created_at desc);
create index if not exists permit_service_orders_user_idx
  on public.permit_service_orders(user_id, created_at desc);
create index if not exists permit_service_orders_status_idx
  on public.permit_service_orders(status, created_at desc);

-- Add the relationship after the table exists. Existing beta/full-service requests
-- remain "waived" so prior cases are never unexpectedly charged.
do $$
begin
  alter table public.permit_concierge_requests
    add constraint permit_concierge_requests_revenue_order_fk
    foreign key (revenue_order_id) references public.permit_service_orders(id) on delete set null;
exception
  when duplicate_object then null;
end $$;

alter table public.permit_service_orders enable row level security;

drop policy if exists "Owners can view permit service orders" on public.permit_service_orders;
create policy "Owners can view permit service orders"
on public.permit_service_orders for select to authenticated
using ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

drop policy if exists "Admins can manage permit service orders" on public.permit_service_orders;
create policy "Admins can manage permit service orders"
on public.permit_service_orders for all to authenticated
using (public.is_project_pilot_admin())
with check (public.is_project_pilot_admin());

grant select on public.permit_service_orders to authenticated;

create or replace function public.touch_permit_service_order_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists permit_service_orders_touch on public.permit_service_orders;
create trigger permit_service_orders_touch
before update on public.permit_service_orders
for each row execute function public.touch_permit_service_order_updated_at();

comment on table public.permit_service_orders is
'One-time Project Pilot Full-Service Permit Concierge coordination purchases. Government permit fees, licensed-professional services, design/engineering work, and third-party charges are separate unless explicitly included.';

-- END 017_revenue_completion_4_0.sql

-- BEGIN 018_loyalty_referrals_4_1.sql
-- Project Pilot 4.1 — simple loyalty and referral loop
-- Give $10, Get $10: referred user gets a $10 Permit Concierge credit at claim;
-- referrer earns a $10 credit after the referred user's first paid Concierge order.


-- Normalize only unpaid pre-4.1 Concierge requests to the new $99 base offer.
-- Paid/refunded historical orders keep their original recorded amounts.
update public.permit_concierge_requests
set service_fee_cents = 9900, updated_at = now()
where payment_status in ('pending','cancelled')
  and service_started_at is null
  and coalesce(service_fee_cents, 0) <> 9900;

create table if not exists public.referral_codes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.referral_attributions (
  id uuid primary key default gen_random_uuid(),
  referred_user_id uuid not null unique references auth.users(id) on delete cascade,
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  referral_code text not null,
  status text not null default 'signed_up' check (status in ('signed_up','qualified','rewarded','reversed')),
  qualified_order_id uuid references public.permit_service_orders(id) on delete set null,
  referred_credit_cents integer not null default 1000 check (referred_credit_cents >= 0),
  referrer_reward_cents integer not null default 1000 check (referrer_reward_cents >= 0),
  created_at timestamptz not null default now(),
  qualified_at timestamptz,
  rewarded_at timestamptz,
  reversed_at timestamptz,
  check (referred_user_id <> referrer_user_id)
);

create index if not exists referral_attributions_referrer_idx
  on public.referral_attributions(referrer_user_id, created_at desc);

create table if not exists public.permit_service_credit_ledger (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  amount_cents integer not null check (amount_cents <> 0),
  reason text not null,
  idempotency_key text not null unique,
  related_user_id uuid references auth.users(id) on delete set null,
  related_order_id uuid references public.permit_service_orders(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists permit_service_credit_ledger_user_idx
  on public.permit_service_credit_ledger(user_id, created_at desc);

alter table public.referral_codes enable row level security;
alter table public.referral_attributions enable row level security;
alter table public.permit_service_credit_ledger enable row level security;

drop policy if exists "Users can view their referral code" on public.referral_codes;
create policy "Users can view their referral code"
on public.referral_codes for select to authenticated
using (user_id = auth.uid() or public.is_project_pilot_admin());

drop policy if exists "Users can view their referral activity" on public.referral_attributions;
create policy "Users can view their referral activity"
on public.referral_attributions for select to authenticated
using (referred_user_id = auth.uid() or referrer_user_id = auth.uid() or public.is_project_pilot_admin());

drop policy if exists "Users can view their Project Pilot credits" on public.permit_service_credit_ledger;
create policy "Users can view their Project Pilot credits"
on public.permit_service_credit_ledger for select to authenticated
using (user_id = auth.uid() or public.is_project_pilot_admin());

grant select on public.referral_codes to authenticated;
grant select on public.referral_attributions to authenticated;
grant select on public.permit_service_credit_ledger to authenticated;

comment on table public.referral_codes is 'Stable share codes used by the Project Pilot Give $10, Get $10 referral program.';
comment on table public.referral_attributions is 'One referrer per referred Project Pilot account. Rewards qualify after the referred user completes a paid Permit Concierge order.';
comment on table public.permit_service_credit_ledger is 'Append-only Project Pilot credit ledger. Positive amounts earn credit; negative amounts apply credit to Permit Concierge.';

-- END 018_loyalty_referrals_4_1.sql

-- 4.1 verification
DO $$
BEGIN
  IF to_regclass('public.permit_service_orders') IS NULL THEN
    RAISE EXCEPTION 'Project Pilot 4.1 verification failed: permit_service_orders was not created.';
  END IF;
  IF to_regclass('public.permit_service_authorizations') IS NULL THEN
    RAISE EXCEPTION 'Project Pilot 4.1 verification failed: permit_service_authorizations was not created.';
  END IF;
  IF to_regclass('public.referral_codes') IS NULL THEN
    RAISE EXCEPTION 'Project Pilot 4.1 verification failed: referral_codes was not created.';
  END IF;
  IF to_regclass('public.permit_service_credit_ledger') IS NULL THEN
    RAISE EXCEPTION 'Project Pilot 4.1 verification failed: permit_service_credit_ledger was not created.';
  END IF;
END $$;

SELECT 'Project Pilot 4.1 cumulative upgrade complete' AS result;
