-- Project Pilot Sprint 3.3
-- Permit Application Builder: reviewed application packets, portal-entry progress,
-- export history, and applicant review audit fields.
-- Run after migrations 012, 013, and 014.

create extension if not exists "pgcrypto";

alter table public.permit_cases
  add column if not exists application_packet_version text not null default '',
  add column if not exists application_packet_generated_at timestamptz,
  add column if not exists application_packet_status text not null default 'not_started',
  add column if not exists portal_field_progress jsonb not null default '{}'::jsonb,
  add column if not exists applicant_review_name text not null default '',
  add column if not exists applicant_review_confirmed_at timestamptz;

do $$
begin
  alter table public.permit_cases
    add constraint permit_cases_application_packet_status_check
    check (application_packet_status in ('not_started','draft','ready','exported','portal_entry','submitted'));
exception
  when duplicate_object then null;
end $$;

create table if not exists public.permit_application_exports (
  id uuid primary key default gen_random_uuid(),
  permit_case_id uuid not null references public.permit_cases(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  export_type text not null default 'packet_snapshot' check (export_type in ('packet_snapshot','printable_html','portal_field_map','structured_json')),
  packet_version text not null default '',
  packet_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.permit_application_exports enable row level security;

drop policy if exists "Project owners can view permit application exports" on public.permit_application_exports;
create policy "Project owners can view permit application exports"
on public.permit_application_exports for select to authenticated
using ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

drop policy if exists "Project owners can create permit application exports" on public.permit_application_exports;
create policy "Project owners can create permit application exports"
on public.permit_application_exports for insert to authenticated
with check ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

drop policy if exists "Project owners can delete permit application exports" on public.permit_application_exports;
create policy "Project owners can delete permit application exports"
on public.permit_application_exports for delete to authenticated
using ((user_id = auth.uid() and public.owns_project(project_id)) or public.is_project_pilot_admin());

grant select, insert, delete on public.permit_application_exports to authenticated;

create index if not exists permit_application_exports_case_idx
  on public.permit_application_exports(permit_case_id, created_at desc);
create index if not exists permit_application_exports_user_idx
  on public.permit_application_exports(user_id, created_at desc);

comment on table public.permit_application_exports is
'Immutable snapshots of homeowner-reviewed permit application packets generated by Project Pilot. Official submission, signatures, identity verification, professional seals, and government payments remain controlled by the applicant, authorized professional, or governing authority.';
