import "../release.css";

export const metadata = { title: "Project Pilot Terms" };

export default function TermsPage() {
  return (
    <main className="releaseDocument">
      <header><a href="/">Project Pilot</a><span>Terms of Use and Service Terms</span></header>
      <article>
        <p className="releaseEyebrow">LAST UPDATED AUGUST 16, 2026</p>
        <h1>Clear rules for free project tools, permit coordination, referrals, and contractor introductions.</h1>
        <p>These terms explain how Project Pilot provides free project-planning and permit tools, optional paid Permit Concierge coordination, referral credits, contractor matching, and qualified introductions. By using the service, you agree to these terms.</p>

        <h2>1. Free Project Pilot tools</h2>
        <p>Homeowners may use the Project Pilot workspace and guided permit tools without a homeowner subscription. Free tools can include project planning, estimated ranges, AI-assisted guidance, permit-route research, application-information organization, checklists, document organization, visual concepts, and contractor search. Free access does not include human Permit Concierge labor unless Project Pilot expressly says otherwise.</p>
        <p>Project Pilot is not a contractor, architect, engineer, attorney, permit office, inspector, or financial adviser. Users remain responsible for confirming requirements, prices, qualifications, and signed agreements.</p>

        <h2>2. Permit Concierge</h2>
        <p>Homeowners may purchase Permit Concierge for the one-time Project Pilot coordination fee displayed before checkout. The service can include project intake review, jurisdiction and filing-route verification, application-information preparation, document organization, administrative agency coordination where permitted, correction tracking, inspection coordination, and closeout tracking.</p>
        <p>Project Pilot will try to minimize the customer&apos;s administrative work, but a government agency or professional may require the applicant to personally sign, verify identity, use an applicant-controlled account, make a government payment, obtain notarization, or obtain work or documents from a licensed professional. Project Pilot will not impersonate a customer or professional or bypass those requirements.</p>
        <p>The Project Pilot fee does not include government permit or filing fees, plan-review fees, licensed-professional services, architectural or engineering work, surveys, trade work, notarization, professional seals, third-party reports, testing, or other outside charges unless checkout expressly says otherwise. Government approval is not guaranteed.</p>

        <h2>3. Permit Concierge cancellations and refunds</h2>
        <p>If a customer cancels while the case remains at intake and before substantive coordination work begins, Project Pilot may issue a refund through the original payment method. Once material research, preparation, agency coordination, filing work, correction work, or other substantive service has been performed, refund eligibility may be reduced or denied to the extent permitted by applicable law. Government and third-party charges are governed by the party that collected them.</p>
        <p>When a qualifying Permit Concierge order is refunded, Project Pilot credit used on that order may be restored. Referral rewards generated by the refunded transaction may be reversed.</p>

        <h2>4. Referral and loyalty credits</h2>
        <p>Project Pilot may offer referral or loyalty credits. Under the current Give $10, Get $10 program, an eligible new user who joins through a valid referral link receives the displayed Project Pilot credit toward Permit Concierge, and the referrer earns the displayed reward after the referred user completes a qualifying paid Permit Concierge order.</p>
        <p>Referral credits are promotional Project Pilot service credits, not cash, and are not transferable or redeemable for cash. Project Pilot may set reasonable eligibility windows, per-order credit limits, anti-abuse rules, and program changes. Self-referrals, duplicate accounts, fraud, or manipulation may void credits.</p>

        <h2>5. Best Match recommendations</h2>
        <p>Contractors cannot pay for higher placement. Best Match results may consider specialty, service area, verification, availability, project size, response history, customer feedback, and completed Project Pilot activity. A match score is an aid, not a guarantee of quality, availability, price, or project outcome.</p>

        <h2>6. Contractor verification</h2>
        <p>Project Pilot may review registration, licensing, insurance, service areas, and profile information. Contractors must keep their information accurate and notify Project Pilot when a license, registration, or insurance document changes. Verification does not replace the customer&apos;s own due diligence.</p>

        <h2>7. Qualified introduction fees</h2>
        <p>Contractors may join and maintain a profile without a monthly fee. When Project Pilot presents a project opportunity, the fixed introduction fee is displayed before acceptance. The contractor is charged only after choosing to accept and completing checkout. Payment does not affect ranking.</p>
        <ul><li>Projects up to $5,000: $25 introduction fee</li><li>$5,001–$15,000: $50 introduction fee</li><li>$15,001–$50,000: $100 introduction fee</li><li>Over $50,000: $150 introduction fee</li></ul>
        <p>The fee purchases access to a qualified introduction. It does not guarantee that the customer will request an estimate, hire the contractor, approve a proposal, or complete a project.</p>

        <h2>8. Lead review and credits</h2>
        <p>A contractor may request review when contact information is invalid, the request is duplicated, the project is materially outside the stated service area, the customer did not request contact, or another contractor had already been hired before acceptance. Project Pilot may issue a credit or refund after review. Failure to win the project, customer price objections, or ordinary competition do not automatically qualify.</p>

        <h2>9. Agreements between users</h2>
        <p>Homeowners and contractors negotiate construction pricing, scope, schedule, warranties, deposits, contracts, change orders, and construction payments directly. Project Pilot is not a party to their construction agreement and does not collect construction deposits or project payments.</p>

        <h2>10. Payments and disputes</h2>
        <p>Paid service and introduction payments are processed by a third-party payment provider. The customer or contractor authorizes the displayed charge when completing checkout. Chargebacks, fraud, or payment abuse may result in account restrictions while the matter is reviewed.</p>

        <h2>11. User responsibilities</h2>
        <p>Users must provide accurate information, protect account credentials, use the service lawfully, and avoid harassment, fraud, manipulation of rankings, referral abuse, or misuse of contact information. Project Pilot may suspend accounts that create safety, trust, payment, or compliance risks.</p>

        <h2>12. Limitation of service</h2>
        <p>Project Pilot is provided on an as-available basis. The platform does not guarantee that every jurisdiction, permit link, estimate, contractor, lead, government timeline, or project record will be complete or error-free. Permit approval and inspection outcomes are controlled by the governing authority. Users should independently verify decisions that affect safety, law, property, or substantial spending.</p>

        <h2>13. Changes</h2>
        <p>Project Pilot may update these terms as services, fees, referral programs, and laws change. The price and material scope of a paid service will be shown before checkout. Material changes to contractor introduction fees will be shown before a contractor accepts a new introduction.</p>

        <div className="releaseNotice"><strong>Business review recommended</strong><p>These terms support the operating workflow in Project Pilot 4.5. A qualified attorney should review them for the final business entity, launch jurisdictions, refund practices, referral program, and applicable consumer-protection requirements before broad paid advertising.</p></div>
      </article>
    </main>
  );
}
